import type { Metadata } from "next";
import { VisualEditing } from "next-sanity";
import { Geist, Geist_Mono } from "next/font/google";
import { draftMode } from "next/headers";

import { DisableDraftMode } from "@/components/custom/DisableDraftMode";
import { MenuNavBar } from "@/components/custom/MenuNavBar";
import { SanityLive } from "@/sanity/lib/live";

import { ThemeProvider } from "../lib/theme-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MenuNavBar />
          {children}
          <SanityLive />
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <p>Here</p>
              <VisualEditing />
            </>
          )}
        </ThemeProvider>
      </body>
    </html>
  );
}
