import type { Metadata } from 'next';
import { VisualEditing } from 'next-sanity';
import { Geist, Geist_Mono } from 'next/font/google';
import { draftMode } from 'next/headers';

import { DisableDraftMode } from '@/components/custom/DisableDraftMode';
import { MenuNavBar } from '@/components/custom/MenuNavBar';
import { SanityLive } from '@/sanity/lib/live';

import { ThemeProvider } from '../lib/theme-provider';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="fixed flex h-16 w-full items-center justify-between border-b-1 border-gray-500 bg-white/80 px-8 backdrop-blur-sm">
          <div>Rodney Martinez</div>
          <MenuNavBar />
        </div>
        {children}
        <SanityLive />
        {(await draftMode()).isEnabled && (
          <>
            <DisableDraftMode />
            <p>Here</p>
            <VisualEditing />
          </>
        )}
      </body>
    </html>
  );
}
